-- AlterTable
ALTER TABLE `watermark_jobs`
  MODIFY `position` ENUM(
    'TOP_LEFT',
    'TOP_CENTER',
    'TOP_RIGHT',
    'MIDDLE_LEFT',
    'CENTER',
    'MIDDLE_RIGHT',
    'BOTTOM_LEFT',
    'BOTTOM_CENTER',
    'BOTTOM_RIGHT'
  ) NOT NULL,
  MODIFY `status` ENUM(
    'PENDING',
    'PROCESSING',
    'COMPLETED',
    'FAILED',
    'CANCELLED'
  ) NOT NULL DEFAULT 'PENDING',
  ADD COLUMN `layout` ENUM('SINGLE', 'TILED') NOT NULL DEFAULT 'SINGLE',
  ADD COLUMN `rotation` DOUBLE NOT NULL DEFAULT 0,
  ADD COLUMN `offsetX` DOUBLE NOT NULL DEFAULT 0,
  ADD COLUMN `offsetY` DOUBLE NOT NULL DEFAULT 0,
  ADD COLUMN `fontFamily` VARCHAR(50) NOT NULL DEFAULT 'Arial',
  ADD COLUMN `fontSize` DOUBLE NOT NULL DEFAULT 0.045,
  ADD COLUMN `textColor` CHAR(7) NOT NULL DEFAULT '#FFFFFF',
  ADD COLUMN `strokeColor` CHAR(7) NOT NULL DEFAULT '#000000',
  ADD COLUMN `strokeWidth` DOUBLE NOT NULL DEFAULT 2;
